### ISSUE TITLE
call back issue

### ISSUE THREAD

**Issue by furley** [frnhr/simple-user-ordering#2]
I am getting this as a response after a user is dropped. The save is failing. (using WP 3.6.1)

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'SimpleUserOrdering_Plugin' does not have a method 'my_action_callback' in {...}/wp-includes/plugin.php on line 406

**Comment by frnhr** [comment]
In line 35 replace "my_action_callback" with "ajax_update".

A typo on my part, will fix.

Thanks for your interest! :)

**Comment by furley** [comment]
yep.. just found that myself. thanks.
